### ISSUE TITLE
FIDO2

### ISSUE THREAD

**Issue by MeikTranel** [MeikTranel/MigrationSupport#1]
**Project:**
URL: https://github.com/abergs/fido2-net-lib
Description: Package to support the new WebAuthN standard in .NET web projects.

**What am i looking for?**
Guidance regarding SourceLink

**Issues i have had doing it by myself: (OPTIONAL)**
Not able to verify with confidence that SourceLink was setup correctly.

**Comment by MeikTranel** [comment]
@abergs i have confirmed that sourcelink is working:

This is the screen when querying sourcefiles from your project for the first time:
![devenv_2018-11-29_16-15-22](https://user-images.githubusercontent.com/6466560/49231514-64963180-f3f2-11e8-9414-323bffcf77f5.png)

This is me stepping into your sourcecode from a consumers perspective using hard DLL reference and copying the PDB to the debug output directory:
![image](https://user-images.githubusercontent.com/6466560/49231483-50eacb00-f3f2-11e8-8a5c-aceaf270a303.png)

I will document how to go about verifying this locally easily in #7

**Comment by MeikTranel** [comment]
I still see some tweaks i can do help you with your overall development experience - both as maintainer and as a consumer.

**Comment by abergs** [comment]
That's really great!

**Comment by MeikTranel** [comment]
I actually found a bug in your library - this one is pretty damn rare! Now i can finally show my boss why exactly net462 was retroactively declared not netstandard2.0 compliant. Really neat.

"System.Security.Cryptography.ECPoint" is part of netstandard2.0 but not of net462 (only via PlatformSupportExtensions).

Because you only ever tested netcoreapp2.0 this was never visible. When adding netcoreapp2.0;net462 in there it runs into type loading exceptions for some tests.

Really damn neat.

**Comment by abergs** [comment]
Hahaha. That's a really amazing find!
But do we declare net462 anywhere or was this an improvement you tried but that exposed the bug?

**Comment by abergs** [comment]
Did you want me to clarify the project structures?
The reason for lifting in the projects are to avoid package poisoning as discussed here https://github.com/abergs/fido2-net-lib/issues/7.

**Comment by MeikTranel** [comment]
I found this issue by adding net462 to the test project targetframeworks. this way you test both major netstandard2.0 implentations.

As for the package poisoning i ask you this? What happens if someone else uses CBOR as a direct or indirect dependency. Now you have two libraries randomly overwriting eachother in the application output directory.
Because Strong-Naming libraries is actively encouraged again (see https://docs.microsoft.com/en-us/dotnet/standard/library-guidance) this means there will be issues with binding redirects. Binding redirections is a .NET Framework only system. When having such conflicts the common workaround is enabling automatic binding redirect generation in the application projects.

You have two options here: Either you say, you trust NuGet, MSBuild and the dotnet-sdk to work this out for you or you deploy the CBOR types by yourself. You choose the latter. This means essentially you accept the risk that consumers using both CBOR and your package have to write MSBuild workarounds to produce repeatable builds. By producing a binary you also accept the risk that ABI(and in some more less common cases even API) incompatability (which in a low-level heavy package like CBOR isn't unlikely) will happen.

I would suggest the following: Either use the PackageReference and trust the dotnet-sdk to fix this for you *OR* embed the CBOR namespaces directly in your library by adding only the CSharp files as Compile-Includes. This way you don't produce additional binaries, which means no non-determinism in consumers builds. If you expose ABI or APIs from CBOR with your own, you will still produce incompatibility, but this way consumers will be forced to actively patch from the CBOR package types to your types - which in my books sounds much more sane than "let's hope ABI/API didn't change".

**Comment by MeikTranel** [comment]
When using packagereference also consider using floating versions, so that version 3.4 or 3.5 (which both have the same APIs subset of 3.4) can both be used - this helps when other projects depend on a more specified OTHER version of the package, which still is SemVer-Compatible with your package.

**Comment by abergs** [comment]
I believe the Compile-Includes would be a good alternative. We don't expose CBOR objects as a feature of the library and CBOR is after all not that common in the application layer. Might need to double check some signatures which accept DTO's with CBOR properties though.

**Comment by MeikTranel** [comment]
Can i do this with the Chaos.NaCL stuff as well? The project itself doesn't produce a nuget package, so you are kind of forced to do stuff like this.
Right now dotnet pack does produce a nuget package for Chaos.NaCL and expects you to deploy both (Fido has a package dependency on it which is really not that nice 😄). You have similar options here: Compile Include (1 DLL) or remain with project reference but set IsPackable to false so that Fido2-Lib-Net has the Chaos.NaCL DLL directly inside the package instead of a dependency.

**Comment by abergs** [comment]
I believe the compile include is fine here ad well. The projects are quite small and I do not count on any consumers having these installed and it's used only internally.

So yes!

**Comment by MeikTranel** [comment]
Nice. will do this as soon as i come home 😉
