### ISSUE TITLE
Consultation on .NET project internals

### ISSUE THREAD

**Issue by adrukh** [MeikTranel/MigrationSupport#2]
**Project:**
We're @snyksec, and we provide a service that keeps developer's projects secure! We don't really need help migrating anything, but we would appreciate the opportunity to reach out to domain experts and discuss the .NET ecosystem and our approach to it.

**What am i looking for?**
- Better understand .NET concepts (framework vs core, targetFrameworks, system dependencies, etc.)
- Exchange ideas on how we can better analyze the dependencies of any .NET project, both on a dev environment (dotnet cli, msbuild, etc.) as well as remotely (say, just a .csproj file).

**Issues i have had doing it by myself: (OPTIONAL)**
We already provide an extensive offering around .NET as part of our service, seeking to learn more and improve!

**Special Requirements**
We're a commercial entity, so some NDA-related paperwork will most likely be involved... In exchange, we act as a commercial entity and pay for consultation! :)

**Comment by MeikTranel** [comment]
Currently i want to focus on doing the OSS work first. Also as mentioned in the kick-off post:
> P.P.S.: Also this has no commercial background whatsoever - i'm not currently looking for a job nor do i plan to commercialize this in any way.

**Comment by adrukh** [comment]
Very clear, understood and more than reasonable!

I will just say that there are numerous open source users and maintainers using our service, but the fact we are a commercial entity prevails. Should this become relevant for you in the future, I'd appreciate a ping.

Closing this issue, thanks again!

**Comment by MeikTranel** [comment]
Definitely. Will do 😉
