### ISSUE TITLE
Soulseek.NET

### ISSUE THREAD

**Issue by MeikTranel** [MeikTranel/MigrationSupport#3]
**Project:**
URL: https://github.com/jpdillingham/Soulseek.NET
Description: Library for soulseek networking protocol

**What am i looking for?**
Mainly CICD support - NuGet Package Deployment

**Issues i have had doing it by myself: (OPTIONAL)**
This can include past experiences, fears and/or roadblocks.

**Comment by MeikTranel** [comment]
Hey @jpdillingham, i'm looking at your project right now and have some questions:

- Do you want your stylecop ruleset to only apply in Debug-Configuration?
- Do you have any preferences when it comes to build scripts? (Cake, MSBuild,...?)

**Comment by jpdillingham** [comment]
Having stylecop apply only in debug would be nice.  If that were the case I'd want to set up a `develop` branch and build pushes as debug, as well as PRs to master, then for master build in release and deploy.  Unless you can think of a better way, of course :)

Regarding build scripts i don't have a strong preference as long as it's cross platform.  The pipeline config uses bash so far but it definitely crossed my mind that a script would be desirable for local ops.

Thanks for taking this on!

**Comment by MeikTranel** [comment]
It's just a little cleanup and some testing on my own Azure DevOps instance before i can open up a PR.
Some questions though:

- What is your primary IDE? VS or VSCode? Would you care about some rough presets for VSCode?
- What OS do you mostly develop on?

**Comment by jpdillingham** [comment]
VS on Windows.  I'm not personally interested in VSCode right now since (as far as I remember) it has poor analyzer support but you can toss in presets if that might help others.

**Comment by MeikTranel** [comment]
I just found out your code analysis rules were never applied 😄 
Now that i'm fixing that everything's lighting up like a christmas tree 😄

**Comment by jpdillingham** [comment]
Yep definitely a ways to go there :)

**Comment by MeikTranel** [comment]
Wow this Ruleset stuff is really tedious - The largest issue here is that with roslyn analyzers now being the way to go, old Visual Studio analyzers and rulesets are interfering; your old ruleset file had listed rule settings for rules contained in the "Managed Binary Analysis" ruleset. This is a visual studio only ruleset, which is what we want to avoid.
Nowadays we want rules to be provided by analyzer nuget packages: One you had already installed "StyleCop.Analyzers". I installed the other central analyzer package for you: "Microsoft.CodeQuality.Analyzers" which contains rules which used to be in the visual studio analyzers - but not all of them - some haven't been ported yet, some have been removed as the team no longer believes they are good rules.
One important change is the way how you override default rule severity in VS2017 and especially VS2019 (VS2019 removes some of the legacy configuration screens that produced unsupported rule configs) - i made a quick GIF on how to use the analyzers and how to set them in a way that modifies it in your custom ruleset.

![2018-12-08_13-55-35](https://user-images.githubusercontent.com/6466560/49686190-36e77180-faf1-11e8-983a-462dcb32e8a1.gif)

If you do have to change some severity in the future, please do it like i did in the GIF.

For now i removed all unsupported rule configs from the ruleset and moved the rules that continue to exist in roslyn analyzer packages to the correct analyzerid/namespace (this one is really important for manual editing: a rule has to be in the right rules node in the XML. the ID is the name of the assembly and the namespace is the namespace the rule type resides in)

**Comment by jpdillingham** [comment]
Thanks for digging in to that.  Will these work properly in VSCode, or is it still limited to VS?

**Comment by MeikTranel** [comment]
That's what i was aiming for. Both VSCode and Rider (i think) use problem matchers (essentially just regexes) to read from build output. So the idea is, if the warning appears in the console log, vscode picks them up with a regex. Because the msbuild warning api also lets you put in line numbers this works on a super simple level.
