### ISSUE TITLE
Migrating .net4.5 library to .net standard

### ISSUE THREAD

**Issue by rikimaru0345** [MeikTranel/MigrationSupport#9]
**Project:**
URL: https://github.com/rikimaru0345/Ceras
Synopsis: A binary serializer, similar to MessagePack-CSharp

**What am i looking for?** / **Special Requirements**
On the most basic level:
1) I want people to be able to use my library on every platform, not just .net4.5.
However I don't know how to do it. Would I need multiple project files? Or is a single .net standard 2.0 project enough so that users on .net4.x, Unity(mono .net4.x equivalent), and .net core can use it?
 
2) Some considerations about required APIs.
The main thing to consider is that Ceras heavily uses `System.Linq.Expressions`.
I'm pretty sure the newest .net standard supports everything Ceras uses, but maybe there might be some complications?

3) At the moment I'm using AppVeyor to compile, and create a nuget package (which is then automatically published to nuget). I guess the nuspec file would have to be changed to create multiple packages depending on the target framework? Or maybe a single .net standard package would be enough so everyone can use it?

4) I'm aware that there are some APIs related to `Type`, `MemberInfo`, etc... that have changed, but I'm confident that updating them myself should be no problem!

**What problems stopped me from doing this myself before? (OPTIONAL)**
No previous experience with nuget, and only minimal the .net core / standard ecosystem.
I'd love to learn more about all of those things but at the moment I don't have as much time to devote to this as I'd like to.

**Comment by rikimaru0345** [comment]
Hey, in the meantime a user of my lib came along and started a PR that does the .net standard targetting!
I accepted it but I'm not sure if its done right. The nuget package seems to work though

**Comment by MeikTranel** [comment]
He got most of it right. I'll just rebase my fork and resolve the conflicts. My changes go a little deeper than just net core though. I have sourcelink and all that jazz in it too

**Comment by MeikTranel** [comment]
You could help by exporting your appveyor config to your repository though. it's kinda hard to guesswork around configs in your private settings. In Appveyor you can press "Export YML" and it gives you file that you can put in your repository. Appveyor will then read this file for settings. This is a little more sane to work with.

**Comment by rikimaru0345** [comment]
Oh, you are completely right, I didn't think about that, In fact I wasn't aware that you could export the configuration, sorry!

I exported the config and commited it to the root folder https://github.com/rikimaru0345/Ceras/commit/fc6df0080d95bffbc2e79dbc7e65a4c2986d6ce3
